# Generated by Django 4.0.10 on 2024-04-16 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_aksiya_category_file_modelimage_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0, verbose_name='Расход')),
                ('costType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.costtype', verbose_name='Тип продажи')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('photo', models.TextField(blank=True, verbose_name='Фото товара')),
                ('costIn', models.FloatField(default=0, verbose_name='Внутренние расходы')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='Категория')),
                ('costs', models.ManyToManyField(blank=True, to='core.cost', verbose_name='Costs')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CostChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateChanged', models.DateTimeField(auto_now_add=True, verbose_name='Дата измнения')),
                ('costs', models.ManyToManyField(blank=True, to='core.cost', verbose_name='Costs')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'История изменений продаж',
                'verbose_name_plural': 'Истории изменений продаж',
            },
        ),
    ]
