# Generated by Django 4.0.10 on 2024-04-22 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_icon_category_nameen_alter_category_namekg'),
        ('user', '0001_initial'),
        ('core', '0002_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0, verbose_name='Count')),
                ('soldCost', models.FloatField(default=0, verbose_name='Стоимость продажи')),
                ('costType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.costtype', verbose_name='Тип продажи')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказной товар',
                'verbose_name_plural': 'Заказные товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('totalCost', models.FloatField(default=0, verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('archive', 'Архив')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('dateDelivered', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.agent', verbose_name='Агент')),
                ('costType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.costtype', verbose_name='Тип продажи')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.driver', verbose_name='Водитель')),
                ('items', models.ManyToManyField(blank=True, to='core.orderitem', verbose_name='Товары')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
