# Generated by Django 4.0.10 on 2024-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_lat_order_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=250, verbose_name='Наименование код'),
        ),
    ]
