# Generated by Django 4.0.10 on 2024-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='bonusAmount',
            field=models.FloatField(default=0, verbose_name='Бонус'),
        ),
    ]
