# Generated by Django 4.0.10 on 2024-05-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_onec_code'),
        ('core', '0008_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agent', verbose_name='Агент')),
                ('friDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friDriver', to='user.driver', verbose_name='Водитель в пятницу')),
                ('friStores', models.ManyToManyField(blank=True, related_name='friStores', to='user.store', verbose_name='Магазины в пятницу')),
                ('monDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monDriver', to='user.driver', verbose_name='Водитель в понедельник')),
                ('monStores', models.ManyToManyField(blank=True, related_name='monStores', to='user.store', verbose_name='Магазины в понедельник')),
                ('satDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satDriver', to='user.driver', verbose_name='Водитель в субботу')),
                ('satStores', models.ManyToManyField(blank=True, related_name='satStores', to='user.store', verbose_name='Магазины в субботу')),
                ('sunDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunDriver', to='user.driver', verbose_name='Водитель в воскресенье')),
                ('sunStores', models.ManyToManyField(blank=True, related_name='sunStores', to='user.store', verbose_name='Магазины в воскресенье')),
                ('thuDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thuDriver', to='user.driver', verbose_name='Водитель в четверг')),
                ('thuStores', models.ManyToManyField(blank=True, related_name='thuStores', to='user.store', verbose_name='Магазины в четверг')),
                ('tueDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tueDriver', to='user.driver', verbose_name='Водитель во вторник')),
                ('tueStores', models.ManyToManyField(blank=True, related_name='tueStores', to='user.store', verbose_name='Магазины во вторник')),
                ('wedDriver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedDriver', to='user.driver', verbose_name='Водитель в среду')),
                ('wedStores', models.ManyToManyField(blank=True, related_name='wedStores', to='user.store', verbose_name='Магазины в среду')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
    ]
