# Generated by Django 4.0.10 on 2024-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shablon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delComment',
            field=models.TextField(blank=True, verbose_name='Комментарий доставщика'),
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.TextField(blank=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.CharField(blank=True, max_length=250, verbose_name='Подпись'),
        ),
    ]
