# Generated by Django 4.0.10 on 2024-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_delcomment_order_photo_order_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=250, verbose_name='Автор'),
        ),
    ]
