# Generated by Django 4.0.10 on 2024-05-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sync_oneC',
            field=models.BooleanField(default=False, verbose_name='Статус синхронизации'),
        ),
    ]
