# Generated by Django 4.0.10 on 2024-06-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_dayplan_datevisit'),
        ('core', '0012_order_is_sync_onec'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amountLeft',
            field=models.FloatField(default=0, verbose_name='Остаток суммы'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('not_paid', 'Не оплачено'), ('half', 'Частично оплачено')], default='not_paid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('archive', 'Архив'), ('cancelled', 'Отменен'), ('returned', 'Возврат')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TransactionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Транзакция заказов',
                'verbose_name_plural': 'Транзакции заказов',
            },
        ),
    ]
