# Generated by Django 4.0.10 on 2024-06-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_amountleft_order_paymentstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionorder',
            name='store',
        ),
    ]
