# Generated by Django 4.0.10 on 2024-06-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_store_region_store_store_agent'),
        ('core', '0014_remove_transactionorder_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
                ('addedItems', models.ManyToManyField(blank=True, related_name='addedItems', to='core.orderitem', verbose_name='Добавленные товары')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.modeladmin', verbose_name='Администратор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Заказ')),
                ('removeItems', models.ManyToManyField(blank=True, related_name='removeItems', to='core.orderitem', verbose_name='Удаленные товары')),
            ],
            options={
                'verbose_name': 'История изменения заказов',
                'verbose_name_plural': 'Истории изменений заказов',
            },
        ),
    ]
