# Generated by Django 4.0.10 on 2024-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес'),
        ),
    ]
