# Generated by Django 4.0.10 on 2024-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isSale',
            field=models.BooleanField(default=False, verbose_name='Is sale?'),
        ),
        migrations.AddField(
            model_name='item',
            name='saleCost',
            field=models.FloatField(default=0, verbose_name='Цена расспродажи'),
        ),
    ]
