# Generated by Django 4.0.10 on 2024-07-25 15:29

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_item_issale_item_salecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oneC_code',
            field=core.models.NoStripCharField(blank=True, max_length=250, verbose_name='Наименование код'),
        ),
    ]
