# Generated by Django 4.0.10 on 2024-07-25 16:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_item_onec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=250, validators=[core.models.no_trim_validator], verbose_name='Наименование код'),
        ),
    ]
