# Generated by Django 4.0.10 on 2024-07-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='oneC_code',
        ),
    ]
