# Generated by Django 4.0.10 on 2024-07-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_item_onec_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
    ]
