# Generated by Django 4.0.10 on 2024-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_returnsorder_returnsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsitem',
            name='soldCost',
            field=models.FloatField(default=0, verbose_name='Sold cost'),
        ),
    ]
