# Generated by Django 4.0.10 on 2024-04-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_aksiya_category_file_modelimage_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='nameEn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='nameKg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Аталышы'),
        ),
    ]
