# Generated by Django 4.0.10 on 2024-07-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.TextField(blank=True, null=True, verbose_name='Тестовый'),
        ),
    ]
