# Generated by Django 4.0.10 on 2024-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='one_guid',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='guid'),
        ),
    ]
