# Generated by Django 4.0.10 on 2024-08-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_costtype_one_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtype',
            name='guid_organic',
            field=models.TextField(blank=True, verbose_name='guid_organic'),
        ),
        migrations.AlterField(
            model_name='costtype',
            name='one_guid',
            field=models.TextField(blank=True, null=True, verbose_name='guid'),
        ),
    ]
