# Generated by Django 4.0.10 on 2024-04-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('visited', 'Посещено')], default='new', max_length=20, verbose_name='Статус')),
                ('photo', models.TextField(blank=True, verbose_name='Ccылка на фото')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('madeOrder', models.BooleanField(default=False, verbose_name='Заказано')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'План магазин',
                'verbose_name_plural': 'Планы магазина',
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='monday', max_length=50, verbose_name='День недели')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('archive', 'Архив')], default='new', max_length=20, verbose_name='Статус')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agent', verbose_name='Агент')),
                ('stores', models.ManyToManyField(blank=True, to='user.store', verbose_name='Магазины')),
            ],
            options={
                'verbose_name': 'Дневной план',
                'verbose_name_plural': 'Дневные планы',
            },
        ),
    ]
