# Generated by Django 4.0.10 on 2024-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_planstore_dayplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-04 12:30:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
