# Generated by Django 4.0.10 on 2024-05-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_store_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='stores',
            field=models.ManyToManyField(blank=True, to='user.planstore', verbose_name='Магазины'),
        ),
    ]
