# Generated by Django 4.0.10 on 2024-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_dayplan_driver_alter_dayplan_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='stores_plan',
            field=models.ManyToManyField(blank=True, to='user.planstore', verbose_name='Планы Магазин'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='stores',
            field=models.ManyToManyField(blank=True, to='user.store', verbose_name='Магазины'),
        ),
    ]
