# Generated by Django 4.0.10 on 2024-05-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_dayplan_stores_plan_alter_dayplan_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='stores',
        ),
    ]
