# Generated by Django 4.0.10 on 2024-05-21 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_dayplan_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
