# Generated by Django 4.0.10 on 2024-05-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_dayplan_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.FloatField(default=0, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='store',
            name='docs',
            field=models.TextField(blank=True, verbose_name='Документ'),
        ),
    ]
