# Generated by Django 4.0.10 on 2024-05-23 07:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_store_area_store_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='docs',
        ),
        migrations.AddField(
            model_name='store',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Документы'),
        ),
    ]
