# Generated by Django 4.0.10 on 2024-05-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_onec_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='dateVisit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата посещения'),
        ),
    ]
