# Generated by Django 4.0.10 on 2024-06-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_region'),
        ('user', '0011_dayplan_datevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.region', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.agent', verbose_name='Агент'),
        ),
    ]
