# Generated by Django 4.0.10 on 2024-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_store_region_store_store_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='guid',
            field=models.CharField(blank=True, max_length=250, verbose_name='GUID'),
        ),
    ]
