# Generated by Django 4.0.10 on 2024-08-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_costtype_one_guid'),
        ('user', '0013_store_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.region', verbose_name='Район'),
        ),
    ]
