# Generated by Django 4.0.10 on 2024-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_store_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250, verbose_name='Пользователь')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('request_body', models.TextField(verbose_name='Request body')),
                ('bElim_response_body', models.TextField(blank=True, verbose_name='Бай элим response')),
                ('organic_response_body', models.TextField(blank=True, verbose_name='Органик response')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Логи пользователей',
                'verbose_name_plural': 'Логи пользователей',
            },
        ),
    ]
