# Generated by Django 4.0.10 on 2025-01-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_agent_user_alter_user_onec_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
    ]
